In [1]:
import duckdb
import pandas as pd

In [7]:
#SQL query to show the parking_violation_codes table create below and limit 5 to only see the first 5 rows
#sql_query = '''
#SELECT * FROM parking_violation_codes LIMIT 5
#'''

#shows sql tables (file.sql) inside the nyc_parking_violations folder
#sql_query = '''
#show tables
#'''

# 97 is the number of rows the dataset has
#sql_query = '''
#SELECT * FROM ref_model
#'''

#view bronze table
#sql_query = '''
#SELECT * FROM bronze_parking_violations LIMIT 3
#'''

#view silver table
#sql_query = '''
#SELECT * FROM silver_violation_tickets LIMIT 3
#'''

#view gold table
sql_query = '''
SELECT * FROM gold_ticket_metrics
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

    violation_code  ticket_count  total_revenue_usd
0               36         37064          1853200.0
1                5          3477           869250.0
2               21         12149           789685.0
3               14          5047           580405.0
4               40          3902           448730.0
..             ...           ...                ...
71              23             1               60.0
72              41            18                0.0
73               0            14                NaN
74              94             1                NaN
75              95             4                NaN

[76 rows x 3 columns]

In [6]:
#parking_violation_codes is the dataset we want to import
# CREATE OR REPLACE TABLE parking_violation_codes -> creates a new table named parking_violation_codes or replaces it if it already exists
#read_csv_auto -> detects csv structure
#normalize_names = True --> makes everything lower case and replaces all special characters with underscores
#basically, it imports all data from dof_parking_violation_codes.csv into the table parking_violation_codes
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
'data/dof_parking_violation_codes.csv',
normalize_names = True
)
'''

#do the same from this file: parking_violations_issued_fiscal_year_2023_sample.csv
sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violation_2023 AS
SELECT *
FROM read_csv_auto(
'data/parking_violations_issued_fiscal_year_2023_sample.csv',
normalize_names = True
)
'''

with duckdb.connect('data/nyc_parking_violations.db') as con: #opens connection to the DuckDB database file
    con.sql(sql_query_import_1) #executes each SQL query
    con.sql(sql_query_import_2)

## Production Environment

In [2]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
'data/dof_parking_violation_codes.csv',
normalize_names = True
)
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violation_2023 AS
SELECT *
FROM read_csv_auto(
'data/parking_violations_issued_fiscal_year_2023_sample.csv',
normalize_names = True
)
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    con.sql(sql_query_import_1) 
    con.sql(sql_query_import_2)

In [3]:
sql_query = '''
show tables              
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3           gold_vehicles_metrics
4          parking_violation_2023
5         parking_violation_codes
6         parking_violations_2023
7        silver_violation_tickets
8       silver_violation_vehicles